# Windows
[shell]
args = ["--cd", "~", "tmux"]
program = "c:/Windows/System32/wsl.exe"

# Linux
# [shell]
# args = []
# program = "/usr/bin/tux"

[cursor]
style = "Beam"

[font]
size = 13.0

[font.normal]
family = "CaskaydiaCove Nerd Font"

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 6

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#181818"
foreground = "#f8f8f2"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[env]
term = "xterm-256color"
